services:
  server:
    build: ./pico-server/
    ports:
      - 5555:5555
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: zeromq-server-java-docker-database
      DB_PORT: 3306
      DB_NAME: pico-data
      DB_USER: user
      DB_PASSWORD: password
    networks:
      - pico_network
  database:
    image: mysql:8.2
    container_name: zeromq-server-java-docker-database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pico-data
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    networks:
      - pico_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  grafana:
    ports:
      - 3000:3000
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana-ubuntu
    volumes:
      - ./grafana-storage:/var/lib/grafana
    networks:
      - pico_network
networks:
  pico_network:
    driver: bridge
